const faq = require("../controllers/faq.controller");
const express = require('express');
const router = express();
const { isAuthenticatedUser, authorizeRoles } = require("../middleware/auth");
router.post("/admin", isAuthenticatedUser, authorizeRoles("admin"), faq.create);
router.patch("/admin/:id",isAuthenticatedUser, authorizeRoles("admin"),faq.update);
router.get("/admin/:id", faq.getId);
router.get("/admin/faq", faq.get);
router.delete("/admin/:id",isAuthenticatedUser, authorizeRoles("admin"),faq.delete);
router.get("/:id", faq.getId);
router.get("/", faq.get);
module.exports = router;